/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wicare;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sreyoshi Ghosh
 */
public class Panel2 extends javax.swing.JPanel {

    //manage enterprise admin
    
      Connection con=null;
        Statement st=null;
        ResultSet rs=null;
          DefaultTableModel model ;
        
    public Panel2() {
        initComponents();
        
       
        jComboBox1.addItem("New Jersy");
        jComboBox1.addItem("Boston");
        jComboBox1.addItem("California");
        
         try {

              con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            st=con.createStatement();

            String s=String.format("select * from enterprise where location='"+jComboBox1.getSelectedItem()+"'");
           rs=st.executeQuery(s);  // execute query
           jComboBox2.removeAllItems();
           
           while(rs.next()){
               
               jComboBox2.addItem(rs.getString(1));
           }
           

        } catch (SQLException ex) {

        }
         
        
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("User Name");
        
        
    }

    
    public void updateTable(){
        
         model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("User Name");
        
          if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i >=0; i--) {
                model.removeRow(i);
            }
        }
        
         try {

            st=con.createStatement();

            String s= "select * from enterprise_detail"  ;
            rs=st.executeQuery(s);  // execute query

            while(rs.next()){

                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});

            }

        } catch (SQLException ex) {

        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(549, 397));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Manage Enterprise Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -10, 290, 70));

        jButton1.setText("Manage Enterprise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 260, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 130));

        jLabel1.setText("Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

        jLabel2.setText("Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel4.setText("User name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 263, 106, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 106, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 106, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //submit button
        String location=(String) jComboBox1.getSelectedItem();
        String enterprise_name=(String) jComboBox2.getSelectedItem();
        String username=jTextField1.getText();
        String password=jPasswordField1.getText();

        String name=jTextField2.getText();


        try {

            st=con.createStatement();

            String s=String.format("insert into enterprise_detail values('%s','%s','%s','%s','%s')", enterprise_name,location,username,password,name);
            int n=st.executeUpdate(s);  // execute query
            if(n>0)
                JOptionPane.showMessageDialog(null, "Record saved successfully");
            else
                 JOptionPane.showMessageDialog(null, "Record could not be added");

        } catch (SQLException ex) {

        }

        jTextField1.setText("");
     jTextField2.setText("");
      jPasswordField1.setText("");
 
        //-------------------

        if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i >=0; i--) {
                model.removeRow(i);
            }
        }

        try {

            st=con.createStatement();

            String s= "select * from enterprise_detail"  ;
            rs=st.executeQuery(s);  // execute query

            while(rs.next()){

                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});

            }

        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Manage Enterprise button
         MainFrame.p2.setVisible(false);
         MainFrame.p1.setVisible(true);
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //Manage Enterprise admin button
         MainFrame.p2.setVisible(true);
         MainFrame.p1.setVisible(false);
        
         updateTable();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        //location combo box click event
          try {

              con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            st=con.createStatement();

            String s="select * from enterprise where location='"+jComboBox1.getSelectedItem()+"'";
           rs=st.executeQuery(s);  // execute query
           jComboBox2.removeAllItems();
           
           while(rs.next()){
               
               jComboBox2.addItem(rs.getString(1));
           }
           

        } catch (SQLException ex) {

        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
